nodeLinker: node-modules

npmPreapprovedPackages:
  - '@gdc/*'

npmScopes:
  gdc:
    npmAlwaysAuth: true
    npmAuthToken: '${VERDACCIO_TOKEN}'
    npmRegistryServer: 'https://verdaccio.gensdeconfiance.com/'
